version: '3.6'
services:
    payaraservice: 
        image: 192.168.43.253:5000/${VERSION}
        build: ./payara-docker/.
        container_name: webserver
        ports:
        - "4848:4848"
        - "8080:8080"
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
