version: '3.6'
services:
    mariadbservice:
        image: 172.17.0.1:5000/${VERSION}
        build: ./mariadb-docker/.
        container_name: mariadb
        environment: 
        - 'MYSQL_ROOT_PASSWORD=root'
        ports:
        - "3306:3306"
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
    payaraservice: 
        image: 172.17.0.1:5000/${VERSION}
        build: ./payara-docker/.   
        container_name: webserver
        depends_on:
        - mariadbservice
        ports:
        - "4848:4848"
        - "8080:8080"
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
